---
- name: Install dependencies
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Add Grafana APT repository key
  get_url:
    url: "https://packages.grafana.com/gpg.key"
    dest: "/etc/apt/trusted.gpg.d/grafana.gpg"
    mode: '0644'
  become: yes

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  become: yes

- name: Update package cache
  apt:
    update_cache: yes
  become: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
  become: yes

- name: Enable and Start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
  become: yes
